// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inference/streamvesting/query.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f667e3499a650297, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f667e3499a650297, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryVestingScheduleRequest is request type for the Query/VestingSchedule RPC method.
type QueryVestingScheduleRequest struct {
	ParticipantAddress string `protobuf:"bytes,1,opt,name=participant_address,json=participantAddress,proto3" json:"participant_address,omitempty"`
}

func (m *QueryVestingScheduleRequest) Reset()         { *m = QueryVestingScheduleRequest{} }
func (m *QueryVestingScheduleRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVestingScheduleRequest) ProtoMessage()    {}
func (*QueryVestingScheduleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f667e3499a650297, []int{2}
}
func (m *QueryVestingScheduleRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVestingScheduleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVestingScheduleRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVestingScheduleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVestingScheduleRequest.Merge(m, src)
}
func (m *QueryVestingScheduleRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVestingScheduleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVestingScheduleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVestingScheduleRequest proto.InternalMessageInfo

func (m *QueryVestingScheduleRequest) GetParticipantAddress() string {
	if m != nil {
		return m.ParticipantAddress
	}
	return ""
}

// QueryVestingScheduleResponse is response type for the Query/VestingSchedule RPC method.
type QueryVestingScheduleResponse struct {
	VestingSchedule *VestingSchedule `protobuf:"bytes,1,opt,name=vesting_schedule,json=vestingSchedule,proto3" json:"vesting_schedule,omitempty"`
}

func (m *QueryVestingScheduleResponse) Reset()         { *m = QueryVestingScheduleResponse{} }
func (m *QueryVestingScheduleResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVestingScheduleResponse) ProtoMessage()    {}
func (*QueryVestingScheduleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f667e3499a650297, []int{3}
}
func (m *QueryVestingScheduleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVestingScheduleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVestingScheduleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVestingScheduleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVestingScheduleResponse.Merge(m, src)
}
func (m *QueryVestingScheduleResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVestingScheduleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVestingScheduleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVestingScheduleResponse proto.InternalMessageInfo

func (m *QueryVestingScheduleResponse) GetVestingSchedule() *VestingSchedule {
	if m != nil {
		return m.VestingSchedule
	}
	return nil
}

// QueryTotalVestingAmountRequest is request type for the Query/TotalVestingAmount RPC method.
type QueryTotalVestingAmountRequest struct {
	ParticipantAddress string `protobuf:"bytes,1,opt,name=participant_address,json=participantAddress,proto3" json:"participant_address,omitempty"`
}

func (m *QueryTotalVestingAmountRequest) Reset()         { *m = QueryTotalVestingAmountRequest{} }
func (m *QueryTotalVestingAmountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTotalVestingAmountRequest) ProtoMessage()    {}
func (*QueryTotalVestingAmountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f667e3499a650297, []int{4}
}
func (m *QueryTotalVestingAmountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTotalVestingAmountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTotalVestingAmountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTotalVestingAmountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalVestingAmountRequest.Merge(m, src)
}
func (m *QueryTotalVestingAmountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTotalVestingAmountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalVestingAmountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalVestingAmountRequest proto.InternalMessageInfo

func (m *QueryTotalVestingAmountRequest) GetParticipantAddress() string {
	if m != nil {
		return m.ParticipantAddress
	}
	return ""
}

// QueryTotalVestingAmountResponse is response type for the Query/TotalVestingAmount RPC method.
type QueryTotalVestingAmountResponse struct {
	TotalAmount github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=total_amount,json=totalAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total_amount"`
}

func (m *QueryTotalVestingAmountResponse) Reset()         { *m = QueryTotalVestingAmountResponse{} }
func (m *QueryTotalVestingAmountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTotalVestingAmountResponse) ProtoMessage()    {}
func (*QueryTotalVestingAmountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f667e3499a650297, []int{5}
}
func (m *QueryTotalVestingAmountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTotalVestingAmountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTotalVestingAmountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTotalVestingAmountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalVestingAmountResponse.Merge(m, src)
}
func (m *QueryTotalVestingAmountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTotalVestingAmountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalVestingAmountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalVestingAmountResponse proto.InternalMessageInfo

func (m *QueryTotalVestingAmountResponse) GetTotalAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.TotalAmount
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "inference.streamvesting.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "inference.streamvesting.QueryParamsResponse")
	proto.RegisterType((*QueryVestingScheduleRequest)(nil), "inference.streamvesting.QueryVestingScheduleRequest")
	proto.RegisterType((*QueryVestingScheduleResponse)(nil), "inference.streamvesting.QueryVestingScheduleResponse")
	proto.RegisterType((*QueryTotalVestingAmountRequest)(nil), "inference.streamvesting.QueryTotalVestingAmountRequest")
	proto.RegisterType((*QueryTotalVestingAmountResponse)(nil), "inference.streamvesting.QueryTotalVestingAmountResponse")
}

func init() {
	proto.RegisterFile("inference/streamvesting/query.proto", fileDescriptor_f667e3499a650297)
}

var fileDescriptor_f667e3499a650297 = []byte{
	// 583 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6b, 0x13, 0x41,
	0x18, 0xce, 0xf8, 0x51, 0xe8, 0x44, 0xa8, 0x4e, 0x0b, 0xd6, 0x58, 0x36, 0x65, 0xf5, 0x10, 0xaa,
	0xce, 0xd8, 0x68, 0xfd, 0x38, 0x36, 0x1e, 0xc5, 0xd2, 0x26, 0x52, 0xd0, 0x4b, 0x98, 0x6c, 0xc6,
	0xed, 0x60, 0x76, 0x66, 0xbb, 0x33, 0x1b, 0x2c, 0xe2, 0xc5, 0x5f, 0x20, 0x08, 0x5e, 0xfc, 0x03,
	0xe2, 0xc9, 0x9f, 0xd1, 0x63, 0x41, 0x10, 0x0f, 0x7e, 0x91, 0x08, 0xfe, 0x0d, 0xd9, 0x99, 0x89,
	0x24, 0x69, 0x36, 0xa4, 0x5e, 0xb2, 0x9b, 0xf7, 0x7d, 0xde, 0xf7, 0x79, 0x9e, 0x99, 0x87, 0x85,
	0x57, 0xb8, 0x78, 0xc6, 0x12, 0x26, 0x02, 0x46, 0x94, 0x4e, 0x18, 0x8d, 0xba, 0x4c, 0x69, 0x2e,
	0x42, 0xb2, 0x9f, 0xb2, 0xe4, 0x00, 0xc7, 0x89, 0xd4, 0x12, 0x5d, 0xfc, 0x07, 0xc2, 0x23, 0xa0,
	0xd2, 0x05, 0x1a, 0x71, 0x21, 0x89, 0xf9, 0xb5, 0xd8, 0xd2, 0x52, 0x28, 0x43, 0x69, 0x5e, 0x49,
	0xf6, 0xe6, 0xaa, 0x2b, 0xa1, 0x94, 0x61, 0x87, 0x11, 0x1a, 0x73, 0x42, 0x85, 0x90, 0x9a, 0x6a,
	0x2e, 0x85, 0x72, 0xdd, 0xb5, 0x40, 0xaa, 0x48, 0x2a, 0xd2, 0xa2, 0x8a, 0x59, 0x62, 0xd2, 0x5d,
	0x6f, 0x31, 0x4d, 0xd7, 0x49, 0x4c, 0x43, 0x2e, 0x0c, 0xd8, 0x61, 0xbd, 0x61, 0xec, 0x00, 0x15,
	0x48, 0x3e, 0xe8, 0x5f, 0xcd, 0x33, 0x14, 0xd3, 0x84, 0x46, 0x03, 0x46, 0x9c, 0x87, 0x72, 0xcf,
	0xa6, 0x0a, 0xf6, 0x58, 0x3b, 0xed, 0x30, 0x8b, 0xf7, 0x97, 0x20, 0xda, 0xc9, 0x74, 0x6d, 0x9b,
	0x25, 0x75, 0xb6, 0x9f, 0x32, 0xa5, 0xfd, 0x27, 0x70, 0x71, 0xa4, 0xaa, 0x62, 0x29, 0x14, 0x43,
	0x35, 0x38, 0x67, 0xc9, 0x96, 0xc1, 0x2a, 0xa8, 0x14, 0xab, 0x65, 0x9c, 0x73, 0x7e, 0xd8, 0x0e,
	0xd6, 0xe6, 0x0f, 0x7f, 0x94, 0x0b, 0x1f, 0xfe, 0x7c, 0x5a, 0x03, 0x75, 0x37, 0xe9, 0x6f, 0xc1,
	0xcb, 0x66, 0xf5, 0xae, 0x45, 0x36, 0x9c, 0x1c, 0xc7, 0x8c, 0x08, 0x5c, 0x8c, 0x69, 0xa2, 0x79,
	0xc0, 0x63, 0x2a, 0x74, 0x93, 0xb6, 0xdb, 0x09, 0x53, 0x96, 0x6f, 0xbe, 0x8e, 0x86, 0x5a, 0x9b,
	0xb6, 0xe3, 0x2b, 0xb8, 0x32, 0x79, 0x9f, 0xd3, 0xdc, 0x80, 0xe7, 0xc7, 0xad, 0x3b, 0xf5, 0x95,
	0x5c, 0xf5, 0xe3, 0xbb, 0x16, 0xba, 0xa3, 0x05, 0x7f, 0x07, 0x7a, 0x86, 0xf4, 0xb1, 0xd4, 0xb4,
	0xe3, 0xd0, 0x9b, 0x91, 0x4c, 0x85, 0xfe, 0x6f, 0x1f, 0xef, 0x00, 0x2c, 0xe7, 0xee, 0x74, 0x5e,
	0x14, 0x3c, 0xa7, 0xb3, 0x6e, 0x93, 0x9a, 0xfa, 0x32, 0x58, 0x3d, 0x5d, 0x29, 0x56, 0x2f, 0x61,
	0x9b, 0x1c, 0x9c, 0x25, 0x07, 0xbb, 0xe4, 0xe0, 0x07, 0x92, 0x8b, 0xda, 0x46, 0x76, 0xfe, 0x1f,
	0x7f, 0x96, 0x2b, 0x21, 0xd7, 0x7b, 0x69, 0x0b, 0x07, 0x32, 0x22, 0x2e, 0x66, 0xf6, 0x71, 0x43,
	0xb5, 0x9f, 0x13, 0x7d, 0x10, 0x33, 0x65, 0x06, 0x94, 0xbd, 0xab, 0xa2, 0x61, 0xb1, 0xe4, 0xd5,
	0xef, 0x67, 0xe0, 0x59, 0x23, 0x0c, 0xbd, 0x07, 0x70, 0xce, 0x5e, 0x2c, 0xba, 0x96, 0x7b, 0x76,
	0xc7, 0xd3, 0x54, 0xba, 0x3e, 0x1b, 0xd8, 0x9a, 0xf4, 0xef, 0xbc, 0xfe, 0xfc, 0xfb, 0xed, 0xa9,
	0x9b, 0x08, 0x93, 0x38, 0x91, 0xed, 0x34, 0xd0, 0x2a, 0xe0, 0x26, 0xcf, 0xd3, 0xf3, 0x8f, 0xbe,
	0x00, 0xb8, 0x30, 0x76, 0x71, 0xe8, 0xf6, 0x74, 0xe6, 0xc9, 0x19, 0x2c, 0x6d, 0x9c, 0x70, 0xca,
	0x09, 0xdf, 0x35, 0xc2, 0xb7, 0xd1, 0xd6, 0xac, 0xc2, 0xc7, 0x73, 0x49, 0x5e, 0x4e, 0x88, 0xcc,
	0x2b, 0xf4, 0x0d, 0x40, 0x74, 0x3c, 0x14, 0xe8, 0xee, 0x74, 0x95, 0xb9, 0xd1, 0x2c, 0xdd, 0x3b,
	0xf9, 0xa0, 0x73, 0xd8, 0x30, 0x0e, 0x1f, 0xa1, 0x87, 0xb3, 0x3a, 0xb4, 0x69, 0x1d, 0xfc, 0x9b,
	0x68, 0xaf, 0xd6, 0x38, 0xec, 0x79, 0xe0, 0xa8, 0xe7, 0x81, 0x5f, 0x3d, 0x0f, 0xbc, 0xe9, 0x7b,
	0x85, 0xa3, 0xbe, 0x57, 0xf8, 0xda, 0xf7, 0x0a, 0x4f, 0xef, 0x0f, 0xa5, 0x36, 0x97, 0xf0, 0xc5,
	0x38, 0x65, 0x16, 0xe6, 0xd6, 0x9c, 0xf9, 0xba, 0xdd, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xbd,
	0xfa, 0xe6, 0xad, 0x06, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// VestingSchedule queries a participant's full vesting schedule.
	VestingSchedule(ctx context.Context, in *QueryVestingScheduleRequest, opts ...grpc.CallOption) (*QueryVestingScheduleResponse, error)
	// TotalVestingAmount queries the total vesting amount for a participant.
	TotalVestingAmount(ctx context.Context, in *QueryTotalVestingAmountRequest, opts ...grpc.CallOption) (*QueryTotalVestingAmountResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/inference.streamvesting.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VestingSchedule(ctx context.Context, in *QueryVestingScheduleRequest, opts ...grpc.CallOption) (*QueryVestingScheduleResponse, error) {
	out := new(QueryVestingScheduleResponse)
	err := c.cc.Invoke(ctx, "/inference.streamvesting.Query/VestingSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TotalVestingAmount(ctx context.Context, in *QueryTotalVestingAmountRequest, opts ...grpc.CallOption) (*QueryTotalVestingAmountResponse, error) {
	out := new(QueryTotalVestingAmountResponse)
	err := c.cc.Invoke(ctx, "/inference.streamvesting.Query/TotalVestingAmount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// VestingSchedule queries a participant's full vesting schedule.
	VestingSchedule(context.Context, *QueryVestingScheduleRequest) (*QueryVestingScheduleResponse, error)
	// TotalVestingAmount queries the total vesting amount for a participant.
	TotalVestingAmount(context.Context, *QueryTotalVestingAmountRequest) (*QueryTotalVestingAmountResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) VestingSchedule(ctx context.Context, req *QueryVestingScheduleRequest) (*QueryVestingScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VestingSchedule not implemented")
}
func (*UnimplementedQueryServer) TotalVestingAmount(ctx context.Context, req *QueryTotalVestingAmountRequest) (*QueryTotalVestingAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TotalVestingAmount not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inference.streamvesting.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VestingSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVestingScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VestingSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inference.streamvesting.Query/VestingSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VestingSchedule(ctx, req.(*QueryVestingScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TotalVestingAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTotalVestingAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TotalVestingAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inference.streamvesting.Query/TotalVestingAmount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TotalVestingAmount(ctx, req.(*QueryTotalVestingAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inference.streamvesting.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "VestingSchedule",
			Handler:    _Query_VestingSchedule_Handler,
		},
		{
			MethodName: "TotalVestingAmount",
			Handler:    _Query_TotalVestingAmount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inference/streamvesting/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryVestingScheduleRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVestingScheduleRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVestingScheduleRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ParticipantAddress) > 0 {
		i -= len(m.ParticipantAddress)
		copy(dAtA[i:], m.ParticipantAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ParticipantAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVestingScheduleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVestingScheduleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVestingScheduleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VestingSchedule != nil {
		{
			size, err := m.VestingSchedule.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTotalVestingAmountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTotalVestingAmountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTotalVestingAmountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ParticipantAddress) > 0 {
		i -= len(m.ParticipantAddress)
		copy(dAtA[i:], m.ParticipantAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ParticipantAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTotalVestingAmountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTotalVestingAmountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTotalVestingAmountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TotalAmount) > 0 {
		for iNdEx := len(m.TotalAmount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalAmount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryVestingScheduleRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ParticipantAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVestingScheduleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VestingSchedule != nil {
		l = m.VestingSchedule.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTotalVestingAmountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ParticipantAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTotalVestingAmountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TotalAmount) > 0 {
		for _, e := range m.TotalAmount {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVestingScheduleRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVestingScheduleRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVestingScheduleRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParticipantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVestingScheduleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVestingScheduleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVestingScheduleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingSchedule", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.VestingSchedule == nil {
				m.VestingSchedule = &VestingSchedule{}
			}
			if err := m.VestingSchedule.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTotalVestingAmountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTotalVestingAmountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTotalVestingAmountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParticipantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTotalVestingAmountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTotalVestingAmountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTotalVestingAmountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalAmount = append(m.TotalAmount, types.Coin{})
			if err := m.TotalAmount[len(m.TotalAmount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
