// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inference/inference/top_miner.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TopMiner struct {
	Address               string  `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	LastQualifiedStarted  int64   `protobuf:"varint,2,opt,name=last_qualified_started,json=lastQualifiedStarted,proto3" json:"last_qualified_started,omitempty"`
	RewardsPaidCount      int32   `protobuf:"varint,3,opt,name=rewards_paid_count,json=rewardsPaidCount,proto3" json:"rewards_paid_count,omitempty"`
	RewardsPaid           []int64 `protobuf:"varint,4,rep,packed,name=rewards_paid,json=rewardsPaid,proto3" json:"rewards_paid,omitempty"`
	QualifiedPeriods      int32   `protobuf:"varint,5,opt,name=qualified_periods,json=qualifiedPeriods,proto3" json:"qualified_periods,omitempty"`
	MissedPeriods         int32   `protobuf:"varint,6,opt,name=missed_periods,json=missedPeriods,proto3" json:"missed_periods,omitempty"`
	QualifiedTime         int64   `protobuf:"varint,7,opt,name=qualified_time,json=qualifiedTime,proto3" json:"qualified_time,omitempty"`
	MissedTime            int64   `protobuf:"varint,8,opt,name=missed_time,json=missedTime,proto3" json:"missed_time,omitempty"`
	LastUpdatedTime       int64   `protobuf:"varint,9,opt,name=last_updated_time,json=lastUpdatedTime,proto3" json:"last_updated_time,omitempty"`
	FirstQualifiedStarted int64   `protobuf:"varint,10,opt,name=first_qualified_started,json=firstQualifiedStarted,proto3" json:"first_qualified_started,omitempty"`
	InitialPower          int64   `protobuf:"varint,11,opt,name=initial_power,json=initialPower,proto3" json:"initial_power,omitempty"`
	InitialOrder          int32   `protobuf:"varint,12,opt,name=initial_order,json=initialOrder,proto3" json:"initial_order,omitempty"`
}

func (m *TopMiner) Reset()         { *m = TopMiner{} }
func (m *TopMiner) String() string { return proto.CompactTextString(m) }
func (*TopMiner) ProtoMessage()    {}
func (*TopMiner) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b2d66b3485f1dd, []int{0}
}
func (m *TopMiner) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TopMiner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TopMiner.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TopMiner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopMiner.Merge(m, src)
}
func (m *TopMiner) XXX_Size() int {
	return m.Size()
}
func (m *TopMiner) XXX_DiscardUnknown() {
	xxx_messageInfo_TopMiner.DiscardUnknown(m)
}

var xxx_messageInfo_TopMiner proto.InternalMessageInfo

func (m *TopMiner) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TopMiner) GetLastQualifiedStarted() int64 {
	if m != nil {
		return m.LastQualifiedStarted
	}
	return 0
}

func (m *TopMiner) GetRewardsPaidCount() int32 {
	if m != nil {
		return m.RewardsPaidCount
	}
	return 0
}

func (m *TopMiner) GetRewardsPaid() []int64 {
	if m != nil {
		return m.RewardsPaid
	}
	return nil
}

func (m *TopMiner) GetQualifiedPeriods() int32 {
	if m != nil {
		return m.QualifiedPeriods
	}
	return 0
}

func (m *TopMiner) GetMissedPeriods() int32 {
	if m != nil {
		return m.MissedPeriods
	}
	return 0
}

func (m *TopMiner) GetQualifiedTime() int64 {
	if m != nil {
		return m.QualifiedTime
	}
	return 0
}

func (m *TopMiner) GetMissedTime() int64 {
	if m != nil {
		return m.MissedTime
	}
	return 0
}

func (m *TopMiner) GetLastUpdatedTime() int64 {
	if m != nil {
		return m.LastUpdatedTime
	}
	return 0
}

func (m *TopMiner) GetFirstQualifiedStarted() int64 {
	if m != nil {
		return m.FirstQualifiedStarted
	}
	return 0
}

func (m *TopMiner) GetInitialPower() int64 {
	if m != nil {
		return m.InitialPower
	}
	return 0
}

func (m *TopMiner) GetInitialOrder() int32 {
	if m != nil {
		return m.InitialOrder
	}
	return 0
}

func init() {
	proto.RegisterType((*TopMiner)(nil), "inference.inference.TopMiner")
}

func init() {
	proto.RegisterFile("inference/inference/top_miner.proto", fileDescriptor_17b2d66b3485f1dd)
}

var fileDescriptor_17b2d66b3485f1dd = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xc7, 0x1b, 0xb2, 0x9f, 0x6e, 0x0b, 0xac, 0x59, 0xc0, 0xda, 0x43, 0xb6, 0x62, 0x85, 0xa8,
	0x00, 0x35, 0x5a, 0xf1, 0xf1, 0x00, 0xcb, 0x19, 0x6d, 0x09, 0xcb, 0x85, 0x4b, 0xe4, 0xc4, 0xd3,
	0x32, 0x52, 0x13, 0x1b, 0xdb, 0x61, 0xe1, 0x2d, 0x78, 0xac, 0x3d, 0xf6, 0xc8, 0x09, 0xa1, 0xf6,
	0x31, 0xb8, 0xa0, 0xd8, 0x4d, 0x1a, 0x01, 0xb7, 0xc9, 0xff, 0xf7, 0xcb, 0xc8, 0x33, 0x1a, 0x72,
	0x86, 0xe5, 0x0c, 0x34, 0x94, 0x39, 0xc4, 0xdb, 0xca, 0x4a, 0x95, 0x16, 0x58, 0x82, 0x9e, 0x28,
	0x2d, 0xad, 0xa4, 0xf7, 0x5a, 0x34, 0x69, 0xab, 0x93, 0xe3, 0xb9, 0x9c, 0x4b, 0xc7, 0xe3, 0xba,
	0xf2, 0xea, 0x49, 0x94, 0x4b, 0x53, 0x48, 0x13, 0x67, 0xdc, 0x40, 0xfc, 0xe5, 0x3c, 0x03, 0xcb,
	0xcf, 0xe3, 0x5c, 0x62, 0xe9, 0xf9, 0xa3, 0xdf, 0x21, 0x39, 0xb8, 0x92, 0xea, 0x6d, 0xdd, 0x9d,
	0x32, 0xb2, 0xcf, 0x85, 0xd0, 0x60, 0x0c, 0x0b, 0x46, 0xc1, 0xf8, 0x30, 0x69, 0x3e, 0xe9, 0x4b,
	0xf2, 0x60, 0xc1, 0x8d, 0x4d, 0x3f, 0x57, 0x7c, 0x81, 0x33, 0x04, 0x91, 0x1a, 0xcb, 0xb5, 0x05,
	0xc1, 0x6e, 0x8d, 0x82, 0x71, 0x98, 0x1c, 0xd7, 0xf4, 0x5d, 0x03, 0xdf, 0x7b, 0x46, 0x9f, 0x13,
	0xaa, 0xe1, 0x9a, 0x6b, 0x61, 0x52, 0xc5, 0x51, 0xa4, 0xb9, 0xac, 0x4a, 0xcb, 0xc2, 0x51, 0x30,
	0xde, 0x4d, 0xee, 0x6e, 0xc8, 0x94, 0xa3, 0x78, 0x53, 0xe7, 0xf4, 0x09, 0x19, 0x74, 0x6d, 0xb6,
	0x33, 0x0a, 0xc7, 0xe1, 0xc5, 0xce, 0xcd, 0xcf, 0xd3, 0x5e, 0xd2, 0xef, 0xd8, 0xf4, 0x19, 0x39,
	0xda, 0xbe, 0x43, 0x81, 0x46, 0x29, 0x0c, 0xdb, 0xf5, 0x5d, 0x5b, 0x30, 0xf5, 0x39, 0x7d, 0x4c,
	0x6e, 0x17, 0x68, 0x4c, 0xc7, 0xdc, 0x73, 0xe6, 0xd0, 0xa7, 0x1d, 0x6d, 0xdb, 0xd3, 0x62, 0x01,
	0x6c, 0xdf, 0x0d, 0x36, 0x6c, 0xd3, 0x2b, 0x2c, 0x80, 0x9e, 0x92, 0xfe, 0xa6, 0x9b, 0x73, 0x0e,
	0x9c, 0x43, 0x7c, 0xe4, 0x84, 0xa7, 0xe4, 0xc8, 0x2d, 0xaa, 0x52, 0x82, 0xdb, 0x46, 0x3b, 0x74,
	0xda, 0x9d, 0x1a, 0x7c, 0xf0, 0xb9, 0x73, 0x5f, 0x93, 0x87, 0x33, 0xd4, 0xff, 0xdd, 0x2a, 0x71,
	0x7f, 0xdc, 0x77, 0xf8, 0x9f, 0xb5, 0x9e, 0x91, 0x21, 0x96, 0x68, 0x91, 0x2f, 0x52, 0x25, 0xaf,
	0x41, 0xb3, 0xbe, 0xb3, 0x07, 0x9b, 0x70, 0x5a, 0x67, 0x5d, 0x49, 0x6a, 0x01, 0x9a, 0x0d, 0xdc,
	0xd8, 0x8d, 0x74, 0x59, 0x67, 0x17, 0x97, 0x37, 0xab, 0x28, 0x58, 0xae, 0xa2, 0xe0, 0xd7, 0x2a,
	0x0a, 0xbe, 0xaf, 0xa3, 0xde, 0x72, 0x1d, 0xf5, 0x7e, 0xac, 0xa3, 0xde, 0xc7, 0x57, 0x73, 0xb4,
	0x9f, 0xaa, 0x6c, 0x92, 0xcb, 0x22, 0x56, 0x5a, 0x8a, 0x2a, 0xb7, 0x26, 0xc7, 0xbf, 0xee, 0xf2,
	0x6b, 0xf7, 0x46, 0xbf, 0x29, 0x30, 0xd9, 0x9e, 0xbb, 0xaa, 0x17, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x89, 0x46, 0x49, 0xce, 0xc7, 0x02, 0x00, 0x00,
}

func (m *TopMiner) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TopMiner) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TopMiner) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.InitialOrder != 0 {
		i = encodeVarintTopMiner(dAtA, i, uint64(m.InitialOrder))
		i--
		dAtA[i] = 0x60
	}
	if m.InitialPower != 0 {
		i = encodeVarintTopMiner(dAtA, i, uint64(m.InitialPower))
		i--
		dAtA[i] = 0x58
	}
	if m.FirstQualifiedStarted != 0 {
		i = encodeVarintTopMiner(dAtA, i, uint64(m.FirstQualifiedStarted))
		i--
		dAtA[i] = 0x50
	}
	if m.LastUpdatedTime != 0 {
		i = encodeVarintTopMiner(dAtA, i, uint64(m.LastUpdatedTime))
		i--
		dAtA[i] = 0x48
	}
	if m.MissedTime != 0 {
		i = encodeVarintTopMiner(dAtA, i, uint64(m.MissedTime))
		i--
		dAtA[i] = 0x40
	}
	if m.QualifiedTime != 0 {
		i = encodeVarintTopMiner(dAtA, i, uint64(m.QualifiedTime))
		i--
		dAtA[i] = 0x38
	}
	if m.MissedPeriods != 0 {
		i = encodeVarintTopMiner(dAtA, i, uint64(m.MissedPeriods))
		i--
		dAtA[i] = 0x30
	}
	if m.QualifiedPeriods != 0 {
		i = encodeVarintTopMiner(dAtA, i, uint64(m.QualifiedPeriods))
		i--
		dAtA[i] = 0x28
	}
	if len(m.RewardsPaid) > 0 {
		dAtA2 := make([]byte, len(m.RewardsPaid)*10)
		var j1 int
		for _, num1 := range m.RewardsPaid {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintTopMiner(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x22
	}
	if m.RewardsPaidCount != 0 {
		i = encodeVarintTopMiner(dAtA, i, uint64(m.RewardsPaidCount))
		i--
		dAtA[i] = 0x18
	}
	if m.LastQualifiedStarted != 0 {
		i = encodeVarintTopMiner(dAtA, i, uint64(m.LastQualifiedStarted))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTopMiner(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTopMiner(dAtA []byte, offset int, v uint64) int {
	offset -= sovTopMiner(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TopMiner) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTopMiner(uint64(l))
	}
	if m.LastQualifiedStarted != 0 {
		n += 1 + sovTopMiner(uint64(m.LastQualifiedStarted))
	}
	if m.RewardsPaidCount != 0 {
		n += 1 + sovTopMiner(uint64(m.RewardsPaidCount))
	}
	if len(m.RewardsPaid) > 0 {
		l = 0
		for _, e := range m.RewardsPaid {
			l += sovTopMiner(uint64(e))
		}
		n += 1 + sovTopMiner(uint64(l)) + l
	}
	if m.QualifiedPeriods != 0 {
		n += 1 + sovTopMiner(uint64(m.QualifiedPeriods))
	}
	if m.MissedPeriods != 0 {
		n += 1 + sovTopMiner(uint64(m.MissedPeriods))
	}
	if m.QualifiedTime != 0 {
		n += 1 + sovTopMiner(uint64(m.QualifiedTime))
	}
	if m.MissedTime != 0 {
		n += 1 + sovTopMiner(uint64(m.MissedTime))
	}
	if m.LastUpdatedTime != 0 {
		n += 1 + sovTopMiner(uint64(m.LastUpdatedTime))
	}
	if m.FirstQualifiedStarted != 0 {
		n += 1 + sovTopMiner(uint64(m.FirstQualifiedStarted))
	}
	if m.InitialPower != 0 {
		n += 1 + sovTopMiner(uint64(m.InitialPower))
	}
	if m.InitialOrder != 0 {
		n += 1 + sovTopMiner(uint64(m.InitialOrder))
	}
	return n
}

func sovTopMiner(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTopMiner(x uint64) (n int) {
	return sovTopMiner(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TopMiner) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTopMiner
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TopMiner: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TopMiner: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTopMiner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTopMiner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastQualifiedStarted", wireType)
			}
			m.LastQualifiedStarted = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastQualifiedStarted |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardsPaidCount", wireType)
			}
			m.RewardsPaidCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RewardsPaidCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTopMiner
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.RewardsPaid = append(m.RewardsPaid, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTopMiner
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTopMiner
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTopMiner
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.RewardsPaid) == 0 {
					m.RewardsPaid = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTopMiner
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.RewardsPaid = append(m.RewardsPaid, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardsPaid", wireType)
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QualifiedPeriods", wireType)
			}
			m.QualifiedPeriods = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QualifiedPeriods |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MissedPeriods", wireType)
			}
			m.MissedPeriods = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MissedPeriods |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QualifiedTime", wireType)
			}
			m.QualifiedTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QualifiedTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MissedTime", wireType)
			}
			m.MissedTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MissedTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdatedTime", wireType)
			}
			m.LastUpdatedTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastUpdatedTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstQualifiedStarted", wireType)
			}
			m.FirstQualifiedStarted = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FirstQualifiedStarted |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialPower", wireType)
			}
			m.InitialPower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitialPower |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialOrder", wireType)
			}
			m.InitialOrder = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTopMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitialOrder |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTopMiner(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTopMiner
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTopMiner(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTopMiner
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTopMiner
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTopMiner
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTopMiner
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTopMiner
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTopMiner
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTopMiner        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTopMiner          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTopMiner = fmt.Errorf("proto: unexpected end of group")
)
