// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package inference

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_EpochPerformanceSummary                        protoreflect.MessageDescriptor
	fd_EpochPerformanceSummary_epoch_index            protoreflect.FieldDescriptor
	fd_EpochPerformanceSummary_participant_id         protoreflect.FieldDescriptor
	fd_EpochPerformanceSummary_inference_count        protoreflect.FieldDescriptor
	fd_EpochPerformanceSummary_missed_requests        protoreflect.FieldDescriptor
	fd_EpochPerformanceSummary_earned_coins           protoreflect.FieldDescriptor
	fd_EpochPerformanceSummary_rewarded_coins         protoreflect.FieldDescriptor
	fd_EpochPerformanceSummary_burned_coins           protoreflect.FieldDescriptor
	fd_EpochPerformanceSummary_validated_inferences   protoreflect.FieldDescriptor
	fd_EpochPerformanceSummary_invalidated_inferences protoreflect.FieldDescriptor
	fd_EpochPerformanceSummary_claimed                protoreflect.FieldDescriptor
)

func init() {
	file_inference_inference_epoch_performance_summary_proto_init()
	md_EpochPerformanceSummary = File_inference_inference_epoch_performance_summary_proto.Messages().ByName("EpochPerformanceSummary")
	fd_EpochPerformanceSummary_epoch_index = md_EpochPerformanceSummary.Fields().ByName("epoch_index")
	fd_EpochPerformanceSummary_participant_id = md_EpochPerformanceSummary.Fields().ByName("participant_id")
	fd_EpochPerformanceSummary_inference_count = md_EpochPerformanceSummary.Fields().ByName("inference_count")
	fd_EpochPerformanceSummary_missed_requests = md_EpochPerformanceSummary.Fields().ByName("missed_requests")
	fd_EpochPerformanceSummary_earned_coins = md_EpochPerformanceSummary.Fields().ByName("earned_coins")
	fd_EpochPerformanceSummary_rewarded_coins = md_EpochPerformanceSummary.Fields().ByName("rewarded_coins")
	fd_EpochPerformanceSummary_burned_coins = md_EpochPerformanceSummary.Fields().ByName("burned_coins")
	fd_EpochPerformanceSummary_validated_inferences = md_EpochPerformanceSummary.Fields().ByName("validated_inferences")
	fd_EpochPerformanceSummary_invalidated_inferences = md_EpochPerformanceSummary.Fields().ByName("invalidated_inferences")
	fd_EpochPerformanceSummary_claimed = md_EpochPerformanceSummary.Fields().ByName("claimed")
}

var _ protoreflect.Message = (*fastReflection_EpochPerformanceSummary)(nil)

type fastReflection_EpochPerformanceSummary EpochPerformanceSummary

func (x *EpochPerformanceSummary) ProtoReflect() protoreflect.Message {
	return (*fastReflection_EpochPerformanceSummary)(x)
}

func (x *EpochPerformanceSummary) slowProtoReflect() protoreflect.Message {
	mi := &file_inference_inference_epoch_performance_summary_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_EpochPerformanceSummary_messageType fastReflection_EpochPerformanceSummary_messageType
var _ protoreflect.MessageType = fastReflection_EpochPerformanceSummary_messageType{}

type fastReflection_EpochPerformanceSummary_messageType struct{}

func (x fastReflection_EpochPerformanceSummary_messageType) Zero() protoreflect.Message {
	return (*fastReflection_EpochPerformanceSummary)(nil)
}
func (x fastReflection_EpochPerformanceSummary_messageType) New() protoreflect.Message {
	return new(fastReflection_EpochPerformanceSummary)
}
func (x fastReflection_EpochPerformanceSummary_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_EpochPerformanceSummary
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_EpochPerformanceSummary) Descriptor() protoreflect.MessageDescriptor {
	return md_EpochPerformanceSummary
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_EpochPerformanceSummary) Type() protoreflect.MessageType {
	return _fastReflection_EpochPerformanceSummary_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_EpochPerformanceSummary) New() protoreflect.Message {
	return new(fastReflection_EpochPerformanceSummary)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_EpochPerformanceSummary) Interface() protoreflect.ProtoMessage {
	return (*EpochPerformanceSummary)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_EpochPerformanceSummary) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.EpochIndex != uint64(0) {
		value := protoreflect.ValueOfUint64(x.EpochIndex)
		if !f(fd_EpochPerformanceSummary_epoch_index, value) {
			return
		}
	}
	if x.ParticipantId != "" {
		value := protoreflect.ValueOfString(x.ParticipantId)
		if !f(fd_EpochPerformanceSummary_participant_id, value) {
			return
		}
	}
	if x.InferenceCount != uint64(0) {
		value := protoreflect.ValueOfUint64(x.InferenceCount)
		if !f(fd_EpochPerformanceSummary_inference_count, value) {
			return
		}
	}
	if x.MissedRequests != uint64(0) {
		value := protoreflect.ValueOfUint64(x.MissedRequests)
		if !f(fd_EpochPerformanceSummary_missed_requests, value) {
			return
		}
	}
	if x.EarnedCoins != uint64(0) {
		value := protoreflect.ValueOfUint64(x.EarnedCoins)
		if !f(fd_EpochPerformanceSummary_earned_coins, value) {
			return
		}
	}
	if x.RewardedCoins != uint64(0) {
		value := protoreflect.ValueOfUint64(x.RewardedCoins)
		if !f(fd_EpochPerformanceSummary_rewarded_coins, value) {
			return
		}
	}
	if x.BurnedCoins != uint64(0) {
		value := protoreflect.ValueOfUint64(x.BurnedCoins)
		if !f(fd_EpochPerformanceSummary_burned_coins, value) {
			return
		}
	}
	if x.ValidatedInferences != uint64(0) {
		value := protoreflect.ValueOfUint64(x.ValidatedInferences)
		if !f(fd_EpochPerformanceSummary_validated_inferences, value) {
			return
		}
	}
	if x.InvalidatedInferences != uint64(0) {
		value := protoreflect.ValueOfUint64(x.InvalidatedInferences)
		if !f(fd_EpochPerformanceSummary_invalidated_inferences, value) {
			return
		}
	}
	if x.Claimed != false {
		value := protoreflect.ValueOfBool(x.Claimed)
		if !f(fd_EpochPerformanceSummary_claimed, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_EpochPerformanceSummary) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "inference.inference.EpochPerformanceSummary.epoch_index":
		return x.EpochIndex != uint64(0)
	case "inference.inference.EpochPerformanceSummary.participant_id":
		return x.ParticipantId != ""
	case "inference.inference.EpochPerformanceSummary.inference_count":
		return x.InferenceCount != uint64(0)
	case "inference.inference.EpochPerformanceSummary.missed_requests":
		return x.MissedRequests != uint64(0)
	case "inference.inference.EpochPerformanceSummary.earned_coins":
		return x.EarnedCoins != uint64(0)
	case "inference.inference.EpochPerformanceSummary.rewarded_coins":
		return x.RewardedCoins != uint64(0)
	case "inference.inference.EpochPerformanceSummary.burned_coins":
		return x.BurnedCoins != uint64(0)
	case "inference.inference.EpochPerformanceSummary.validated_inferences":
		return x.ValidatedInferences != uint64(0)
	case "inference.inference.EpochPerformanceSummary.invalidated_inferences":
		return x.InvalidatedInferences != uint64(0)
	case "inference.inference.EpochPerformanceSummary.claimed":
		return x.Claimed != false
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.EpochPerformanceSummary"))
		}
		panic(fmt.Errorf("message inference.inference.EpochPerformanceSummary does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EpochPerformanceSummary) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "inference.inference.EpochPerformanceSummary.epoch_index":
		x.EpochIndex = uint64(0)
	case "inference.inference.EpochPerformanceSummary.participant_id":
		x.ParticipantId = ""
	case "inference.inference.EpochPerformanceSummary.inference_count":
		x.InferenceCount = uint64(0)
	case "inference.inference.EpochPerformanceSummary.missed_requests":
		x.MissedRequests = uint64(0)
	case "inference.inference.EpochPerformanceSummary.earned_coins":
		x.EarnedCoins = uint64(0)
	case "inference.inference.EpochPerformanceSummary.rewarded_coins":
		x.RewardedCoins = uint64(0)
	case "inference.inference.EpochPerformanceSummary.burned_coins":
		x.BurnedCoins = uint64(0)
	case "inference.inference.EpochPerformanceSummary.validated_inferences":
		x.ValidatedInferences = uint64(0)
	case "inference.inference.EpochPerformanceSummary.invalidated_inferences":
		x.InvalidatedInferences = uint64(0)
	case "inference.inference.EpochPerformanceSummary.claimed":
		x.Claimed = false
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.EpochPerformanceSummary"))
		}
		panic(fmt.Errorf("message inference.inference.EpochPerformanceSummary does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_EpochPerformanceSummary) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "inference.inference.EpochPerformanceSummary.epoch_index":
		value := x.EpochIndex
		return protoreflect.ValueOfUint64(value)
	case "inference.inference.EpochPerformanceSummary.participant_id":
		value := x.ParticipantId
		return protoreflect.ValueOfString(value)
	case "inference.inference.EpochPerformanceSummary.inference_count":
		value := x.InferenceCount
		return protoreflect.ValueOfUint64(value)
	case "inference.inference.EpochPerformanceSummary.missed_requests":
		value := x.MissedRequests
		return protoreflect.ValueOfUint64(value)
	case "inference.inference.EpochPerformanceSummary.earned_coins":
		value := x.EarnedCoins
		return protoreflect.ValueOfUint64(value)
	case "inference.inference.EpochPerformanceSummary.rewarded_coins":
		value := x.RewardedCoins
		return protoreflect.ValueOfUint64(value)
	case "inference.inference.EpochPerformanceSummary.burned_coins":
		value := x.BurnedCoins
		return protoreflect.ValueOfUint64(value)
	case "inference.inference.EpochPerformanceSummary.validated_inferences":
		value := x.ValidatedInferences
		return protoreflect.ValueOfUint64(value)
	case "inference.inference.EpochPerformanceSummary.invalidated_inferences":
		value := x.InvalidatedInferences
		return protoreflect.ValueOfUint64(value)
	case "inference.inference.EpochPerformanceSummary.claimed":
		value := x.Claimed
		return protoreflect.ValueOfBool(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.EpochPerformanceSummary"))
		}
		panic(fmt.Errorf("message inference.inference.EpochPerformanceSummary does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EpochPerformanceSummary) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "inference.inference.EpochPerformanceSummary.epoch_index":
		x.EpochIndex = value.Uint()
	case "inference.inference.EpochPerformanceSummary.participant_id":
		x.ParticipantId = value.Interface().(string)
	case "inference.inference.EpochPerformanceSummary.inference_count":
		x.InferenceCount = value.Uint()
	case "inference.inference.EpochPerformanceSummary.missed_requests":
		x.MissedRequests = value.Uint()
	case "inference.inference.EpochPerformanceSummary.earned_coins":
		x.EarnedCoins = value.Uint()
	case "inference.inference.EpochPerformanceSummary.rewarded_coins":
		x.RewardedCoins = value.Uint()
	case "inference.inference.EpochPerformanceSummary.burned_coins":
		x.BurnedCoins = value.Uint()
	case "inference.inference.EpochPerformanceSummary.validated_inferences":
		x.ValidatedInferences = value.Uint()
	case "inference.inference.EpochPerformanceSummary.invalidated_inferences":
		x.InvalidatedInferences = value.Uint()
	case "inference.inference.EpochPerformanceSummary.claimed":
		x.Claimed = value.Bool()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.EpochPerformanceSummary"))
		}
		panic(fmt.Errorf("message inference.inference.EpochPerformanceSummary does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EpochPerformanceSummary) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "inference.inference.EpochPerformanceSummary.epoch_index":
		panic(fmt.Errorf("field epoch_index of message inference.inference.EpochPerformanceSummary is not mutable"))
	case "inference.inference.EpochPerformanceSummary.participant_id":
		panic(fmt.Errorf("field participant_id of message inference.inference.EpochPerformanceSummary is not mutable"))
	case "inference.inference.EpochPerformanceSummary.inference_count":
		panic(fmt.Errorf("field inference_count of message inference.inference.EpochPerformanceSummary is not mutable"))
	case "inference.inference.EpochPerformanceSummary.missed_requests":
		panic(fmt.Errorf("field missed_requests of message inference.inference.EpochPerformanceSummary is not mutable"))
	case "inference.inference.EpochPerformanceSummary.earned_coins":
		panic(fmt.Errorf("field earned_coins of message inference.inference.EpochPerformanceSummary is not mutable"))
	case "inference.inference.EpochPerformanceSummary.rewarded_coins":
		panic(fmt.Errorf("field rewarded_coins of message inference.inference.EpochPerformanceSummary is not mutable"))
	case "inference.inference.EpochPerformanceSummary.burned_coins":
		panic(fmt.Errorf("field burned_coins of message inference.inference.EpochPerformanceSummary is not mutable"))
	case "inference.inference.EpochPerformanceSummary.validated_inferences":
		panic(fmt.Errorf("field validated_inferences of message inference.inference.EpochPerformanceSummary is not mutable"))
	case "inference.inference.EpochPerformanceSummary.invalidated_inferences":
		panic(fmt.Errorf("field invalidated_inferences of message inference.inference.EpochPerformanceSummary is not mutable"))
	case "inference.inference.EpochPerformanceSummary.claimed":
		panic(fmt.Errorf("field claimed of message inference.inference.EpochPerformanceSummary is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.EpochPerformanceSummary"))
		}
		panic(fmt.Errorf("message inference.inference.EpochPerformanceSummary does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_EpochPerformanceSummary) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "inference.inference.EpochPerformanceSummary.epoch_index":
		return protoreflect.ValueOfUint64(uint64(0))
	case "inference.inference.EpochPerformanceSummary.participant_id":
		return protoreflect.ValueOfString("")
	case "inference.inference.EpochPerformanceSummary.inference_count":
		return protoreflect.ValueOfUint64(uint64(0))
	case "inference.inference.EpochPerformanceSummary.missed_requests":
		return protoreflect.ValueOfUint64(uint64(0))
	case "inference.inference.EpochPerformanceSummary.earned_coins":
		return protoreflect.ValueOfUint64(uint64(0))
	case "inference.inference.EpochPerformanceSummary.rewarded_coins":
		return protoreflect.ValueOfUint64(uint64(0))
	case "inference.inference.EpochPerformanceSummary.burned_coins":
		return protoreflect.ValueOfUint64(uint64(0))
	case "inference.inference.EpochPerformanceSummary.validated_inferences":
		return protoreflect.ValueOfUint64(uint64(0))
	case "inference.inference.EpochPerformanceSummary.invalidated_inferences":
		return protoreflect.ValueOfUint64(uint64(0))
	case "inference.inference.EpochPerformanceSummary.claimed":
		return protoreflect.ValueOfBool(false)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.EpochPerformanceSummary"))
		}
		panic(fmt.Errorf("message inference.inference.EpochPerformanceSummary does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_EpochPerformanceSummary) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in inference.inference.EpochPerformanceSummary", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_EpochPerformanceSummary) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EpochPerformanceSummary) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_EpochPerformanceSummary) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_EpochPerformanceSummary) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*EpochPerformanceSummary)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.EpochIndex != 0 {
			n += 1 + runtime.Sov(uint64(x.EpochIndex))
		}
		l = len(x.ParticipantId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.InferenceCount != 0 {
			n += 1 + runtime.Sov(uint64(x.InferenceCount))
		}
		if x.MissedRequests != 0 {
			n += 1 + runtime.Sov(uint64(x.MissedRequests))
		}
		if x.EarnedCoins != 0 {
			n += 1 + runtime.Sov(uint64(x.EarnedCoins))
		}
		if x.RewardedCoins != 0 {
			n += 1 + runtime.Sov(uint64(x.RewardedCoins))
		}
		if x.BurnedCoins != 0 {
			n += 1 + runtime.Sov(uint64(x.BurnedCoins))
		}
		if x.ValidatedInferences != 0 {
			n += 1 + runtime.Sov(uint64(x.ValidatedInferences))
		}
		if x.InvalidatedInferences != 0 {
			n += 1 + runtime.Sov(uint64(x.InvalidatedInferences))
		}
		if x.Claimed {
			n += 2
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*EpochPerformanceSummary)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.Claimed {
			i--
			if x.Claimed {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x50
		}
		if x.InvalidatedInferences != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.InvalidatedInferences))
			i--
			dAtA[i] = 0x48
		}
		if x.ValidatedInferences != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.ValidatedInferences))
			i--
			dAtA[i] = 0x40
		}
		if x.BurnedCoins != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.BurnedCoins))
			i--
			dAtA[i] = 0x38
		}
		if x.RewardedCoins != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.RewardedCoins))
			i--
			dAtA[i] = 0x30
		}
		if x.EarnedCoins != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.EarnedCoins))
			i--
			dAtA[i] = 0x28
		}
		if x.MissedRequests != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.MissedRequests))
			i--
			dAtA[i] = 0x20
		}
		if x.InferenceCount != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.InferenceCount))
			i--
			dAtA[i] = 0x18
		}
		if len(x.ParticipantId) > 0 {
			i -= len(x.ParticipantId)
			copy(dAtA[i:], x.ParticipantId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ParticipantId)))
			i--
			dAtA[i] = 0x12
		}
		if x.EpochIndex != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.EpochIndex))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*EpochPerformanceSummary)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: EpochPerformanceSummary: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: EpochPerformanceSummary: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EpochIndex", wireType)
				}
				x.EpochIndex = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.EpochIndex |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ParticipantId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ParticipantId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field InferenceCount", wireType)
				}
				x.InferenceCount = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.InferenceCount |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MissedRequests", wireType)
				}
				x.MissedRequests = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.MissedRequests |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EarnedCoins", wireType)
				}
				x.EarnedCoins = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.EarnedCoins |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field RewardedCoins", wireType)
				}
				x.RewardedCoins = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.RewardedCoins |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 7:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field BurnedCoins", wireType)
				}
				x.BurnedCoins = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.BurnedCoins |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 8:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ValidatedInferences", wireType)
				}
				x.ValidatedInferences = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.ValidatedInferences |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 9:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field InvalidatedInferences", wireType)
				}
				x.InvalidatedInferences = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.InvalidatedInferences |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 10:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Claimed", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.Claimed = bool(v != 0)
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: inference/inference/epoch_performance_summary.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EpochPerformanceSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EpochIndex            uint64 `protobuf:"varint,1,opt,name=epoch_index,json=epochIndex,proto3" json:"epoch_index,omitempty"`
	ParticipantId         string `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	InferenceCount        uint64 `protobuf:"varint,3,opt,name=inference_count,json=inferenceCount,proto3" json:"inference_count,omitempty"`
	MissedRequests        uint64 `protobuf:"varint,4,opt,name=missed_requests,json=missedRequests,proto3" json:"missed_requests,omitempty"`
	EarnedCoins           uint64 `protobuf:"varint,5,opt,name=earned_coins,json=earnedCoins,proto3" json:"earned_coins,omitempty"`
	RewardedCoins         uint64 `protobuf:"varint,6,opt,name=rewarded_coins,json=rewardedCoins,proto3" json:"rewarded_coins,omitempty"`
	BurnedCoins           uint64 `protobuf:"varint,7,opt,name=burned_coins,json=burnedCoins,proto3" json:"burned_coins,omitempty"`
	ValidatedInferences   uint64 `protobuf:"varint,8,opt,name=validated_inferences,json=validatedInferences,proto3" json:"validated_inferences,omitempty"`
	InvalidatedInferences uint64 `protobuf:"varint,9,opt,name=invalidated_inferences,json=invalidatedInferences,proto3" json:"invalidated_inferences,omitempty"`
	Claimed               bool   `protobuf:"varint,10,opt,name=claimed,proto3" json:"claimed,omitempty"`
}

func (x *EpochPerformanceSummary) Reset() {
	*x = EpochPerformanceSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inference_inference_epoch_performance_summary_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EpochPerformanceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochPerformanceSummary) ProtoMessage() {}

// Deprecated: Use EpochPerformanceSummary.ProtoReflect.Descriptor instead.
func (*EpochPerformanceSummary) Descriptor() ([]byte, []int) {
	return file_inference_inference_epoch_performance_summary_proto_rawDescGZIP(), []int{0}
}

func (x *EpochPerformanceSummary) GetEpochIndex() uint64 {
	if x != nil {
		return x.EpochIndex
	}
	return 0
}

func (x *EpochPerformanceSummary) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *EpochPerformanceSummary) GetInferenceCount() uint64 {
	if x != nil {
		return x.InferenceCount
	}
	return 0
}

func (x *EpochPerformanceSummary) GetMissedRequests() uint64 {
	if x != nil {
		return x.MissedRequests
	}
	return 0
}

func (x *EpochPerformanceSummary) GetEarnedCoins() uint64 {
	if x != nil {
		return x.EarnedCoins
	}
	return 0
}

func (x *EpochPerformanceSummary) GetRewardedCoins() uint64 {
	if x != nil {
		return x.RewardedCoins
	}
	return 0
}

func (x *EpochPerformanceSummary) GetBurnedCoins() uint64 {
	if x != nil {
		return x.BurnedCoins
	}
	return 0
}

func (x *EpochPerformanceSummary) GetValidatedInferences() uint64 {
	if x != nil {
		return x.ValidatedInferences
	}
	return 0
}

func (x *EpochPerformanceSummary) GetInvalidatedInferences() uint64 {
	if x != nil {
		return x.InvalidatedInferences
	}
	return 0
}

func (x *EpochPerformanceSummary) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

var File_inference_inference_epoch_performance_summary_proto protoreflect.FileDescriptor

var file_inference_inference_epoch_performance_summary_proto_rawDesc = []byte{
	0x0a, 0x33, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x70, 0x65, 0x72, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x22, 0xa4, 0x03, 0x0a, 0x17, 0x45,
	0x70, 0x6f, 0x63, 0x68, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x65, 0x70, 0x6f,
	0x63, 0x68, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x27,
	0x0a, 0x0f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x6d, 0x69, 0x73, 0x73, 0x65,
	0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0e, 0x6d, 0x69, 0x73, 0x73, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73,
	0x12, 0x21, 0x0a, 0x0c, 0x65, 0x61, 0x72, 0x6e, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x69, 0x6e, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x65, 0x61, 0x72, 0x6e, 0x65, 0x64, 0x43, 0x6f,
	0x69, 0x6e, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x5f,
	0x63, 0x6f, 0x69, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x65, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x75,
	0x72, 0x6e, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x69, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0b, 0x62, 0x75, 0x72, 0x6e, 0x65, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x12, 0x31, 0x0a,
	0x14, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x13, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73,
	0x12, 0x35, 0x0a, 0x16, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x15, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d,
	0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65,
	0x64, 0x42, 0xca, 0x01, 0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x1c, 0x45,
	0x70, 0x6f, 0x63, 0x68, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x24, 0x63,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0xa2, 0x02, 0x03, 0x49, 0x49, 0x58, 0xaa, 0x02, 0x13, 0x49, 0x6e, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0xca,
	0x02, 0x13, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5c, 0x49, 0x6e, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0xe2, 0x02, 0x1f, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x5c, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x14, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x3a, 0x3a, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inference_inference_epoch_performance_summary_proto_rawDescOnce sync.Once
	file_inference_inference_epoch_performance_summary_proto_rawDescData = file_inference_inference_epoch_performance_summary_proto_rawDesc
)

func file_inference_inference_epoch_performance_summary_proto_rawDescGZIP() []byte {
	file_inference_inference_epoch_performance_summary_proto_rawDescOnce.Do(func() {
		file_inference_inference_epoch_performance_summary_proto_rawDescData = protoimpl.X.CompressGZIP(file_inference_inference_epoch_performance_summary_proto_rawDescData)
	})
	return file_inference_inference_epoch_performance_summary_proto_rawDescData
}

var file_inference_inference_epoch_performance_summary_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_inference_inference_epoch_performance_summary_proto_goTypes = []interface{}{
	(*EpochPerformanceSummary)(nil), // 0: inference.inference.EpochPerformanceSummary
}
var file_inference_inference_epoch_performance_summary_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inference_inference_epoch_performance_summary_proto_init() }
func file_inference_inference_epoch_performance_summary_proto_init() {
	if File_inference_inference_epoch_performance_summary_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inference_inference_epoch_performance_summary_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EpochPerformanceSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inference_inference_epoch_performance_summary_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inference_inference_epoch_performance_summary_proto_goTypes,
		DependencyIndexes: file_inference_inference_epoch_performance_summary_proto_depIdxs,
		MessageInfos:      file_inference_inference_epoch_performance_summary_proto_msgTypes,
	}.Build()
	File_inference_inference_epoch_performance_summary_proto = out.File
	file_inference_inference_epoch_performance_summary_proto_rawDesc = nil
	file_inference_inference_epoch_performance_summary_proto_goTypes = nil
	file_inference_inference_epoch_performance_summary_proto_depIdxs = nil
}
